AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  OriginPath:
    Type: String
    Default: dev

Resources:
  petergeorgantascomCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: petergeorgantas.com
      SubjectAlternativeNames:
        - "*.petergeorgantas.com"
        - georgantas.dev
        - "*.georgantas.dev"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: petergeorgantas.com
          HostedZoneId: Z9U1P15CH72I3
        - DomainName: georgantas.dev
          HostedZoneId: ZO22YLZA59WDO

  petergeorgantascomOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for petergeorgantas.com S3 origin

  petergeorgantascomS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: petergeorgantas.com

  petergeorgantascomS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref petergeorgantascomS3
      PolicyDocument:
        Statement:
        -
          Action:
            - "s3:GetObject"
          Effect: "Allow"
          Resource:
            Fn::Join:
              - ""
              -
                - "arn:aws:s3:::"
                - Ref: "petergeorgantascomS3"
                - "/*"
          Principal:
            CanonicalUser: !GetAtt [petergeorgantascomOriginAccessIdentity, S3CanonicalUserId]

  petergeorgantascomDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt [petergeorgantascomS3, DomainName]
          Id: petergeorgantascomS3Origin
          OriginPath:
            !Join
              - ''
              - - '/'
                - !Ref OriginPath
          S3OriginConfig:
            OriginAccessIdentity:
              !Join
                - ''
                - - 'origin-access-identity/cloudfront/'
                  - !Ref petergeorgantascomOriginAccessIdentity
        Enabled: 'true'
        DefaultRootObject: index.html
        Aliases:
        - petergeorgantas.com
        - www.petergeorgantas.com
        - georgantas.dev
        - www.georgantas.dev
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: 'true'
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: petergeorgantascomS3Origin
          ViewerProtocolPolicy : redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref petergeorgantascomCert
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  petergeorgantascomRoute53Apex:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: petergeorgantas.com.
      Name: petergeorgantas.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt [petergeorgantascomDistribution, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 # Always the same for cloudfront
  petergeorgantascomRoute53WWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: petergeorgantas.com.
      Name: www.petergeorgantas.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt [petergeorgantascomDistribution, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 # Always the same for cloudfront
  georgantasdevRoute53Apex:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: georgantas.dev.
      Name: georgantas.dev
      Type: A
      AliasTarget:
        DNSName: !GetAtt [petergeorgantascomDistribution, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 # Always the same for cloudfront
  georgantasdevRoute53WWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: georgantas.dev.
      Name: www.georgantas.dev
      Type: A
      AliasTarget:
        DNSName: !GetAtt [petergeorgantascomDistribution, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 # Always the same for cloudfront
